version: '3'

services:
  api-cron-tests:
    image: registry.digitalocean.com/margingeek/mg-tests:0.1
    environment:
      - TEST_APP_MODE=prod
    volumes:
      - s-volume:/env/bin  # Mount the s-volume at /env/bin in the container
    command: sh -c "cron && tail -f /var/log/cron.log"
    restart: unless-stopped
volumes:
  s-volume:
    external: true